- name: install docker
  apt:
    name:
      - docker.io
      - nfs-client
    state: present
    update_cache: true

- name: enable docker
  systemd:
    name: docker
    state: started
    enabled: true

- name: Add an k8s apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: install docker
  apt:
    name:
      - "kubeadm={{ k8s_ver }}"
      - "kubelet={{ k8s_ver }}"
      - "kubectl={{ k8s_ver }}"
    state: present
