---
- name: Disable SWAP
  shell:
    cmd: |
      swapoff -a
  args:
    executable: /bin/bash

- name: Remove Swap from fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: enable modules
  community.general.modprobe:
    name: "{{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: set sysctl params
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
  with_items:
    - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }

- name: docker.io / contianerd repo
  block:
    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        filename: docker
        state: present

- name: install containerd and other packages
  apt:
    name:
      - containerd.io
      - nfs-client
      - tmux
      - htop
    state: present
    update_cache: true

# - name: create docker config
#   copy:
#     content: |
#       {
#         "exec-opts": ["native.cgroupdriver=systemd"],
#         "log-driver": "json-file",
#         "log-opts": {
#           "max-size": "100m"
#         },
#         "storage-driver": "overlay2"
#       }
#     dest: /etc/docker/daemon.json

- name: copy containerd config
  copy:
    src: containerd/config.toml
    dest: /etc/containerd/
    mode: "0644"

- name: enable containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: true
    enabled: true

- name: install crictl
  unarchive:
    src: "https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ k8s_common_crictl_ver }}/crictl-{{ k8s_common_crictl_ver }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755

- name: copy crictl config
  copy:
    src: crictl/crictl.yaml
    dest: /etc/
    mode: "0644"

# https://stackoverflow.com/questions/59629319/unable-to-upgrade-connection-pod-does-not-exist
- name: Fix kubelet listen ip
  copy:
    content: |
      KUBELET_EXTRA_ARGS=--node-ip={{ k8s_common_kubelet_listen_ip }}
    dest: /etc/default/kubelet
  when: k8s_common_kubelet_listen_ip is defined

- name: Add an k8s apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s repo
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes

- name: install k8s components
  apt:
    name:
      - "kubeadm={{ k8s_common_k8s_ver }}-00"
      - "kubelet={{ k8s_common_k8s_ver }}-00"
      - "kubectl={{ k8s_common_k8s_ver }}-00"
      - "kubernetes-cni={{ k8s_common_cni_ver }}-00"
    state: present

- name: create .vimrc
  copy:
    content: |
      colorscheme ron
      set number
      set et
      set sw=2 ts=2 sts=2
    dest: "{{ item }}/.vimrc"
  with_items:
    - /root
    - /home/vagrant

- name: bash config
  blockinfile:
    path: "{{ item }}/.bashrc"
    block: |
      source <(kubectl completion bash)
      source <(kubeadm completion bash)
      alias k=kubectl
      complete -F __start_kubectl k
      export do="--dry-run=client -oyaml"
      export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
  with_items:
    - /root
    - /home/vagrant
