kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: ""
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 14.1.1
    helm:
     values: |-
       alertmanager:
        persistentVolume:
          enabled: false
       nodeExporter:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
       server:
        persistentVolume:
          enabled: false
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - prom.k8s.local
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    syncOptions:
      - CreateNamespace=true
