# https://hub.kubeapps.com/charts/ckotzbauer/nfs-client-provisioner
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nfs-client-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nfs-client-provisioner
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: ""
    chart: nfs-client-provisioner
    repoURL: https://ckotzbauer.github.io/helm-charts
    targetRevision: 1.0.2
    helm:
      values: |
        storageClass:
          defaultClass: true
        nfs:
          path: /var/nfs/share
          server: 192.168.111.10
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    syncOptions:
      - CreateNamespace=true
