kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: ""
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.3
    # helm:
    #  values: |-

  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    syncOptions:
      - CreateNamespace=true
