---
### Common tasks
- name: install common packets on vms
  become: true
  hosts: all
  vars:
    k8s_ver: 1.19.0-00
  tasks:
    - name: common tasks
      import_tasks: k8s/common.yml

### Configure master node
- name: configure master node
  become: true
  gather_facts: false
  hosts: masters
  tasks:
    - name: configure master
      import_tasks: k8s/master.yml
    - name: deploy metallb
      import_tasks: k8s/metallb.yml
    - name: deploy nfs storage
      import_tasks: k8s/nfs-storage.yml
    - name: deploy nginx ingress controller
      import_tasks: k8s/nginx-ingress.yml
    - name: install helm3
      import_tasks: k8s/helm3.yml

- name: configure worker node
  become: true
  gather_facts: false
  hosts: nodes
  tasks:
    - name: set join command
      shell: "{{ hostvars['master'].join_command_raw.stdout_lines[0] }} >> worker_register.log"
      args:
        chdir: $HOME
        creates: worker_register.log
