- name: install common packets on vms
  become: true
  hosts: all
  roles:
    - role: k8s_common
      vars:
        k8s_common_ver: "{{ _k8s_version }}"
      tags:
      - common
    - role: k8s_worker
      vars:
        k8s_worker_bootstrap_token: "{{ _k8s_bootstrap_token }}"
        k8s_worker_master_fqdn: "master.{{ _k8s_master_node_ip }}.nip.io"
      tags:
      - worker
