---
### Common tasks
- name: install common packets on vms
  become: true
  hosts: all
  vars:
    k8s_ver: 1.19.0-00
  tasks:
    - name: common tasks
      import_tasks: k8s_common.yml

### Configure master node
- name: configure master node
  become: true
  gather_facts: false
  hosts: all
  vars:
    helm_ver: 3.5.0
  tasks:
    - name: configure master
      import_tasks: k8s_master/master.yml
    - name: deploy metallb
      import_tasks: k8s_master/metallb.yml
    - name: deploy nfs storage
      import_tasks: k8s_master/nfs-storage.yml
    - name: install helm3
      import_tasks: k8s_master/helm3.yml
    - name: deploy nginx ingress controller
      import_tasks: k8s_master/nginx-ingress.yml
    - name: deploy metrics server
      import_tasks: k8s_master/metrics-server.yml
