- name: install common packets on vms
  become: true
  hosts: all
  roles:
    - role: k8s_common
      vars:
        k8s_common_k8s_ver: "{{ _k8s_version }}"
        k8s_common_kubelet_listen_ip: "{{ ansible_enp0s8.ipv4.address }}"
      tags:
      - common
    - role: k8s_worker
      vars:
        k8s_worker_bootstrap_token: "{{ _k8s_bootstrap_token }}"
        k8s_worker_master_fqdn: "{{ _k8s_master_node_ip }}"
      tags:
      - worker
